const data = [
  {
    id: 1,
    name: "Essentials Hoddie White",
    price: 699,
    quantity: 1,
    ratings: 3,
    category: "MEN",
    image: "./images/essentials.png",
  },
  {
    id: 2,
    name: "Levis Mens Dark Jeans",
    price: 240,
    quantity: 1,
    ratings: 4,
    category: "MEN",
    image: "./images/hf30snql@2x.png",
  },
  {
    id: 3,
    name: "Dior Chelsea Boots",
    price: 8000,
    quantity: 1,
    ratings: 4,
    category: "MEN",
    image: "./images/5v67b4jo@2x.png",
  },
  {
    id: 4,
    name: "Dr Martin Boots",
    price: 6000,
    quantity: 1,
    ratings: 2,
    category: "MEN",
    image: "./images/evv02c6j@2x.png",
  },
  {
    id: 5,
    name: "Converse Black Chuks",
    price: 3000,
    quantity: 1,
    ratings: 5,
    category: "MEN",
    image: "./images/i1ho2ra8@2x.png",
  },
  {
    id: 6,
    name: "Levis Jeans Jacket",
    price: 3500,
    quantity: 1,
    ratings: 5,
    category: "MEN",
    image: "./images/8e4cp7rt@2x.png",
  },
  {
    id: 7,
    name: "Mens Arrow Head Necklace",
    price: 3000,
    quantity: 1,
    ratings: 3,
    category: "MEN",
    image: "./images/7064o0yy@2x.png",
  },
  {
    id: 8,
    name: "Zara Suede Jacket",
    price: 9000,
    quantity: 1,
    ratings: 4,
    category: "MEN",
    image: "./images/7ts03xhj@2x.png",
  },
];

export default data;
